y = 20.;
eps = 5.2;
z = y / 0.1;
mW = [0,     10.,   z,          z;...
      45.,   0,     y,          y;...
      22.5,  5.,    0,          eps;...
      22.5,  5.,    eps,        0];

[epr, s_KLD, s_aff, passive] = get_epr_and_bounds(mW);