y = 20.;
eps = 0.5;
z = y / 5;
mW = [0,   10.,   z,          z;...
               45.,  0,   y,          y;...
                22.5,  5.,   0,  eps;...
                22.5,  5.,    eps,       0];

[epr, s_KLD, s_aff, passive] = get_epr_and_bounds(mW);